-- Exact Online financial transaction lines (grootboekmutaties).
-- Source: GET /api/v1/{division}/sync/Financial/TransactionLines
-- Deletions: GET /api/v1/{division}/sync/Deleted (EntityType = 1)

CREATE TABLE IF NOT EXISTS transaction_lines (
    id CHAR(36) NOT NULL,
    division INT NOT NULL,
    timestamp BIGINT NOT NULL,
    entry_id CHAR(36) NULL,
    entry_number INT NULL,
    line_number INT NULL,
    line_type SMALLINT NULL,
    date DATE NULL,
    financial_year SMALLINT NULL,
    financial_period SMALLINT NULL,
    journal_code VARCHAR(20) NULL,
    journal_description VARCHAR(60) NULL,
    gl_account CHAR(36) NULL,
    gl_account_code VARCHAR(30) NULL,
    gl_account_description VARCHAR(60) NULL,
    account CHAR(36) NULL,
    account_code VARCHAR(18) NULL,
    account_name VARCHAR(50) NULL,
    description VARCHAR(60) NULL,
    amount_dc DECIMAL(19, 4) NULL,
    amount_fc DECIMAL(19, 4) NULL,
    currency VARCHAR(10) NULL,
    exchange_rate DECIMAL(19, 6) NULL,
    vat_code VARCHAR(10) NULL,
    vat_code_description VARCHAR(60) NULL,
    vat_percentage DECIMAL(10, 4) NULL,
    vat_type VARCHAR(5) NULL,
    amount_vat_fc DECIMAL(19, 4) NULL,
    amount_vat_base_fc DECIMAL(19, 4) NULL,
    type SMALLINT NULL,
    status SMALLINT NULL,
    invoice_number INT NULL,
    order_number INT NULL,
    your_ref VARCHAR(30) NULL,
    payment_reference VARCHAR(60) NULL,
    payment_discount_amount DECIMAL(19, 4) NULL,
    due_date DATE NULL,
    cost_center VARCHAR(8) NULL,
    cost_center_description VARCHAR(60) NULL,
    cost_unit VARCHAR(8) NULL,
    cost_unit_description VARCHAR(60) NULL,
    project CHAR(36) NULL,
    project_code VARCHAR(20) NULL,
    project_description VARCHAR(60) NULL,
    item CHAR(36) NULL,
    item_code VARCHAR(30) NULL,
    item_description VARCHAR(255) NULL,
    quantity DECIMAL(19, 4) NULL,
    document CHAR(36) NULL,
    document_number INT NULL,
    notes TEXT NULL,
    created DATETIME NULL,
    modified DATETIME NULL,
    deleted_at DATETIME NULL,
    synced_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_division_date (division, date),
    KEY idx_entry_number (entry_number),
    KEY idx_gl_account_code (gl_account_code),
    KEY idx_journal_code (journal_code),
    KEY idx_type (type),
    KEY idx_timestamp (timestamp),
    KEY idx_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS deleted_entities (
    id CHAR(36) NOT NULL,
    division INT NULL,
    entity_type INT NULL,
    entity_key CHAR(36) NOT NULL,
    timestamp BIGINT NOT NULL,
    deleted_date DATETIME NULL,
    synced_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_entity_key (entity_key),
    KEY idx_timestamp (timestamp)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sync_state (
    entity VARCHAR(64) NOT NULL,
    last_timestamp BIGINT NOT NULL,
    last_sync_at DATETIME NOT NULL,
    last_error TEXT NULL,
    PRIMARY KEY (entity)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
